# Generated by Django 5.0.2 on 2024-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_DB',
            fields=[
                ('bklino', models.IntegerField(primary_key='bklino', serialize=False)),
                ('bookname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('publ', models.CharField(max_length=20)),
                ('pgs', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
